package client

import (
	"encoding/xml"
	"errors"
	"reflect"

	"github.com/google/uuid"
)

type SOAPInterface interface {
	toXml() ([]byte, error)
}

type genericReadableRow struct {
	XMLName xml.Name      `xml:"apir:GenericReadableRow"`
	Values  []interface{} `xml:"apir:Values>apir:anyType"`
}

func toGenericReadableRows(rows interface{}) ([]genericReadableRow, error) {
	var interfaces []interface{}
	rv := reflect.ValueOf(rows)
	if rv.Kind() == reflect.Slice {
		for i := 0; i < rv.Len(); i++ {
			interfaces = append(interfaces, rv.Index(i).Interface())
		}
	} else {
		return nil, errors.New("not a slice")
	}
	var genericReadableRows []genericReadableRow
	for _, row := range interfaces {
		var values []interface{}
		fields := reflect.ValueOf(row).NumField()
		for i := 0; i < fields; i++ {
			value := reflect.ValueOf(row).Field(i)
			values = append(values, value.Interface())
		}
		genericReadableRows = append(genericReadableRows, genericReadableRow{Values: values})
	}
	return genericReadableRows, nil
}

type DynamicCategoryType uint8

const (
	DynamicCategoryType_ComputerModel DynamicCategoryType = 1
	DynamicCategoryType_Device        DynamicCategoryType = 2
	DynamicCategoryType_Application   DynamicCategoryType = 4
	DynamicCategoryType_Any           DynamicCategoryType = 255
)

type DynamicCategoryOriginType uint8

const (
	DynamicCategoryOriginType_Automatic DynamicCategoryOriginType = 1
	DynamicCategoryOriginType_Manual    DynamicCategoryOriginType = 2
	DynamicCategoryOriginType_Any       DynamicCategoryOriginType = 255
)

// DynamicCategory represents a dynamic category in WSUS.
//
// Only ID and Type are required.
//
// ID should be a valid UUID (generated by github.com/google/uuid).
//
// Type should be one of the DynamicCategoryType constants.
//
// If supplied, Origin should be one of the DynamicCategoryOriginType constants.
//
// It is recommended to only supply the required fields.
type DynamicCategoryInterface struct {
	XMLName       xml.Name                  `xml:"apir:AddDynamicCategory"`
	ID            uuid.UUID                 `xml:"apir:id"`
	Name          string                    `xml:"apir:name"` // Optional
	Type          DynamicCategoryType       `xml:"apir:type"`
	Origin        DynamicCategoryOriginType `xml:"apir:origin omitempty"`
	IsSyncEnabled bool                      `xml:"apir:isSyncEnabled omitempty"`
	DiscoveryTime int64                     `xml:"apir:discoveryTime omitempty"`
	TargetId      int                       `xml:"apir:targetId omitempty"`
}

func (d DynamicCategoryInterface) toXml() ([]byte, error) {
	return xml.Marshal(d)
}

// DynamicCategories represents a list of dynamic categories.
//
// This is used to add multiple dynamic categories at once
type DynamicCategoriesInterface struct {
	XMLName    xml.Name                   `xml:"apir:AddDynamicCategories"`
	Categories []DynamicCategoryInterface `xml:"apir:categories"`
}

func (d DynamicCategoriesInterface) toXml() ([]byte, error) {
	temp, err := xml.Marshal(d)
	if err != nil {
		return nil, err
	}
	return []byte("<apir:AddDynamicCategories><apir:categories>" + string(temp) + "</apir:categories></apir:AddDynamicCategories>"), nil
}

func (d DynamicCategoriesInterface) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	rows, err := toGenericReadableRows(d.Categories)
	if err != nil {
		return err
	}
	return e.Encode(rows)
}

// NewLanguage represents a locale in WSUS.
type NewLanguageInterface struct {
	XMLName       xml.Name `xml:"apir:AddNewLanguage"`
	ID            int      `xml:"apir:newLanguage>apir:LanguageId"`
	ShortLanguage string   `xml:"apir:newLanguage>apir:ShortLanguage"` // Optional
	LongLanguage  string   `xml:"apir:newLanguage>apir:LongLanguage"`  // Optional
	Enabled       bool     `xml:"apir:newLanguage>apir:Enabled"`
}

func (n NewLanguageInterface) toXml() ([]byte, error) {
	return xml.Marshal(n)
}

// AutomaticUpdateApprovalRule is used to apply automatic update approval rules to WSUS.
type AutomaticUpdateApprovalRuleInterface struct {
	XMLName xml.Name `xml:"apir:ApplyAutomaticUpdateApprovalRule"`
	ID      int      `xml:"apir:ruleId"`
}

func (a AutomaticUpdateApprovalRuleInterface) toXml() ([]byte, error) {
	return xml.Marshal(a)
}

// CatalogSiteGetMetadataAndImport is used to get metadata and import update binaries.
type CatalogSiteGetMetadataAndImportInterface struct {
	XMLName             xml.Name  `xml:"apir:CatalogSiteGetMetadataAndImport"`
	ID                  uuid.UUID `xml:"apir:updateId"`
	DownloadFileDigests []byte    `xml:"apir:downloadFileDigests>apir:base64Binary"` // Optional
}

func (c CatalogSiteGetMetadataAndImportInterface) toXml() ([]byte, error) {
	return xml.Marshal(c)
}

// InstallApprovalRule is used to create an install approval rule.
type InstallApprovalRuleInterface struct {
	XMLName xml.Name `xml:"apir:CreateInstallApprovalRule"`
	Name    string   `xml:"apir:name"`
}

func (c InstallApprovalRuleInterface) toXml() ([]byte, error) {
	return xml.Marshal(c)
}

// DeleteDynamicCategory is used to delete a dynamic category.
type DeleteDynamicCategoryInterface struct {
	XMLName xml.Name  `xml:"apir:DeleteDynamicCategory"`
	ID      uuid.UUID `xml:"apir:id"`
}

func (d DeleteDynamicCategoryInterface) toXml() ([]byte, error) {
	return xml.Marshal(d)
}

// DeleteInstallApprovalRule is used to delete an install approval rule.
type DeleteInstallApprovalRuleInterface struct {
	XMLName xml.Name `xml:"apir:DeleteInstallApprovalRule"`
	ID      int      `xml:"apir:id"`
}

func (d DeleteInstallApprovalRuleInterface) toXml() ([]byte, error) {
	return xml.Marshal(d)
}

// ExecuteGetSigningCertificate is used to get the WSUS signing certificate.
type ExecuteGetSigningCertificateInterface struct {
	XMLName xml.Name `xml:"apir:ExecuteGetSigningCertificate"`
}

func (e ExecuteGetSigningCertificateInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteReplicaSPDeleteDeployment is used to delete a replica deployment.
type ExecuteReplicaSPDeleteDeploymentInterface struct {
	XMLName xml.Name  `xml:"apir:ExecuteReplicaSPDeleteDeployment"`
	ID      uuid.UUID `xml:"apir:id"`
}

func (e ExecuteReplicaSPDeleteDeploymentInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSetSelfSigningCertificate instructs the WSUS server to use a self-signed certificate.
type ExecuteSetSelfSigningCertificateInterface struct {
	XMLName xml.Name `xml:"apir:ExecuteSetSelfSigningCertificate"`
}

func (e ExecuteSetSelfSigningCertificateInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSetSigningCertificate allows specification of a signing certificate.
// The certificate should be in PFX format.
type ExecuteSetSigningCertificateInterface struct {
	XMLName  xml.Name `xml:"apir:ExecuteSetSigningCertificate"`
	Cert     []byte   `xml:"apir:PFXFileContent"`
	Password []byte   `xml:"apir:passwordBytes"` // Optional
}

func (e ExecuteSetSigningCertificateInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPAcceptEula is used to accept the EULA for an update.
// AdminName should be the CN of the user who "accepted" the EULA if provided.
type ExecuteSPAcceptEulaInterface struct {
	XMLName   xml.Name  `xml:"apir:ExecuteSPAcceptEula"`
	ID        uuid.UUID `xml:"apir:id"`
	AdminName string    `xml:"apir:adminName"`              // optional
	UpdateID  uuid.UUID `xml:"apir:updateId>apir:updateId"` // optional
	Revision  int       `xml:"apir:updateId>apir:revision"` // optional if UpdateID is not provided
}

func (e ExecuteSPAcceptEulaInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPAcceptEulaForReplicaDSS is used to accept the EULA for replica downstream servers.
type ExecuteSPAcceptEulaForReplicaDSSInterface struct {
	XMLName xml.Name  `xml:"apir:ExecuteSPAcceptEulaForReplicaDSS"`
	ID      uuid.UUID `xml:"apir:eulaId"`
}

func (e ExecuteSPAcceptEulaForReplicaDSSInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPAddComputerToTargetGroupAllowMultipleGroups is used to add a computer to a target group allowing multiple groups.
type ExecuteSPAddComputerToTargetGroupAllowMultipleGroupsInterface struct {
	XMLName       xml.Name  `xml:"apir:ExecuteSPAddComputerToTargetGroupAllowMultipleGroups"`
	TargetGroupID uuid.UUID `xml:"apir:targetGroupId"`
	ComputerID    int       `xml:"apir:computerId"`
}

func (e ExecuteSPAddComputerToTargetGroupAllowMultipleGroupsInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPCancelAllDownloads is used to cancel all current update downloads.
type ExecuteSPCancelAllDownloadsInterface struct {
	XMLName xml.Name `xml:"apir:ExecuteSPCancelAllDownloads"`
}

func (e ExecuteSPCancelAllDownloadsInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPCacnelDownload is used to cancel a current update download.
type ExecuteSPCancelDownloadInterface struct {
	XMLName  xml.Name  `xml:"apir:ExecuteSPCancelDownload"`
	ID       uuid.UUID `xml:"apir:id>apir:UpdateId"`
	Revision int       `xml:"apir:id>apir:RevisionNumber"`
}

func (e ExecuteSPCancelDownloadInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPCleanupObsoleteComputers deletes obsolete computers from WSUS.
type ExecuteSPCleanupObsoleteComputersInterface struct {
	XMLName xml.Name `xml:"apir:ExecuteSPCleanupObsoleteComputers"`
}

func (e ExecuteSPCleanupObsoleteComputersInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPCleanupUnneededContentFiles deletes unneeded content files from WSUS.
type ExecuteSPCleanupUnneededContentFilesInterface struct {
	XMLName xml.Name `xml:"apir:ExecuteSPCleanupUnneededContentFiles"`
}

func (e ExecuteSPCleanupUnneededContentFilesInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPCleanupUnneededContentFilesPreciseInterface deletes unneeded content files from WSUS, allowing for server targetting and local published files.
type ExecuteSPCleanupUnneededContentFilesPreciseInterface struct {
	XMLName                  xml.Name `xml:"apir:ExecuteSPCleanupUnneededContentFiles2"`
	ServerName               string   `xml:"apir:updateServerName"` // optional
	CleanLocalPublishedFiles bool     `xml:"apir:cleanLocalPublishedContentFiles"`
}

func (e ExecuteSPCleanupUnneededContentFilesPreciseInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPCompressUpdate is used to enable compression for an update.
type ExecuteSPCompressUpdateInterface struct {
	XMLName xml.Name `xml:"apir:ExecuteSPCompressUpdate"`
	ID      int      `xml:"apir:localUpdateId"`
}

func (e ExecuteSPCompressUpdateInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPCountObsoleteUpdatesToCleanup counts the number of obsolete updates to cleanup.
// Use GetSPCountObsoleteUpdatesToCleanupResponse on the response to get the result.
type ExecuteSPCountObsoleteUpdatesToCleanupInterface struct {
	XMLName xml.Name `xml:"apir:ExecuteSPCountObsoleteUpdatesToCleanup"`
}

func (e ExecuteSPCountObsoleteUpdatesToCleanupInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPCountUpdatesToCompress counts the number of updates to compress.
// Use GetSPCountUpdatesToCompressResponse on the response to get the result.
type ExecuteSPCountUpdatesToCompressInterface struct {
	XMLName xml.Name `xml:"apir:ExecuteSPCountUpdatesToCompress"`
}

func (e ExecuteSPCountUpdatesToCompressInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPCreateTargetGroup is used to create a target group.
type ExecuteSPCreateTargetGroupInterface struct {
	XMLName         xml.Name  `xml:"apir:ExecuteSPCreateTargetGroup"`
	TargetGroupName string    `xml:"apir:name"`
	ParentGroupID   uuid.UUID `xml:"apir:parentGroupId"`
}

func (e ExecuteSPCreateTargetGroupInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}

// ExecuteSPCreateTargetGroupPrecise is used to create a target group, allowing for specification of the ID of the group and whether or not the group
// can be added when the server is in replication mode.
type ExecuteSPCreateTargetGroupPreciseInterface struct {
	XMLName         xml.Name  `xml:"apir:ExecuteSPCreateTargetGroup2"`
	TargetGroupName string    `xml:"apir:name"`
	ParentGroupID   uuid.UUID `xml:"apir:parentGroupId"`
	ID              uuid.UUID `xml:"apir:id"`
	FailIfReplica   bool      `xml:"apir:failIfReplica"`
}

func (e ExecuteSPCreateTargetGroupPreciseInterface) toXml() ([]byte, error) {
	return xml.Marshal(e)
}
